name: New issue

on:
  issues:
    types: [opened]

jobs:
  issueCreated:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    permissions:
      issues: write
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get NPM version
        id: get_npm_version
        run: echo "LATEST_VERSION=$(npm view iobroker.shelly@latest version)" >> "$GITHUB_OUTPUT"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Repo ${{ github.event.repository.name }} - ${{ github.event.repository.full_name }}
            Latest beta version is: **${{ steps.get_npm_version.outputs.LATEST_VERSION }}**
